services:
  bot_app:
    image: <yourimagehere>:<yourversionhere>
    container_name: bot_app
    restart: unless-stopped
    depends_on:
      bot_database:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  bot_database:
    image: postgres:latest
    container_name: bot_database
    restart: unless-stopped
    expose:
      - ${DB_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USER}
      PGPORT: ${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data: