services:
  bot_app:
    build:
      context: ./ # The path to your Dockerfile directory
      dockerfile: Dockerfile # Name of your Dockerfile
    container_name: bot_app
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - CMD_MODE=${CMD_MODE}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DB_FILENAME=${DB_FILENAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

volumes:
  pg_data:
