services:
  bot_app:
    image: ghcr.io/whalepower/whalebot:main
    container_name: bot_app
    restart: unless-stopped
    depends_on:
      - bot_database
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - CMD_MODE=${CMD_MODE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CONNECTION_LIMIT=${MYSQL_CONNECTION_LIMIT}

  bot_database:
    image: mysql
    container_name: bot_database
    restart: unless-stopped
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: