services:
  bot_app:
    build:
      context: ./ # The path to your Dockerfile directory
      dockerfile: Dockerfile # Name of your Dockerfile
    container_name: bot_app
    restart: unless-stopped
    env_file:
      - .env